name = "DftFunctionals"
uuid = "6bd331d2-b28d-4fd3-880e-1a1c7f37947f"
authors = ["Michael F. Herbst <info@michael-herbst.com>"]
version = "0.3.1"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ComponentArrays = "0.15"
DiffResults = "1"
ForwardDiff = "1"
Libxc_jll = "5.1.0"
julia = "1.6"

[extras]
Libxc_jll = "a56a6d9d-ad03-58af-ab61-878bf78270d6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Libxc_jll"]
